# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, dlist }:

cabal.mkDerivation (self: {
  pname = "inserts";
  version = "0.1.1";
  src = ./.;
  buildDepends = [ attoparsec dlist ];
  meta = {
    homepage = "http://github.com/tel/inserts";
    description = "Stupid simple bytestring templates";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
